// Package hyperfleet provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package hyperfleet

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for AdapterConditionStatus.
const (
	AdapterConditionStatusFalse   AdapterConditionStatus = "False"
	AdapterConditionStatusTrue    AdapterConditionStatus = "True"
	AdapterConditionStatusUnknown AdapterConditionStatus = "Unknown"
)

// Valid indicates whether the value is a known member of the AdapterConditionStatus enum.
func (e AdapterConditionStatus) Valid() bool {
	switch e {
	case AdapterConditionStatusFalse:
		return true
	case AdapterConditionStatusTrue:
		return true
	case AdapterConditionStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ClusterPlatformSpecType.
const (
	ClusterPlatformSpecTypeGcp ClusterPlatformSpecType = "gcp"
)

// Valid indicates whether the value is a known member of the ClusterPlatformSpecType enum.
func (e ClusterPlatformSpecType) Valid() bool {
	switch e {
	case ClusterPlatformSpecTypeGcp:
		return true
	default:
		return false
	}
}

// Defines values for GCPClusterPlatformEndpointAccess.
const (
	Private          GCPClusterPlatformEndpointAccess = "Private"
	PublicAndPrivate GCPClusterPlatformEndpointAccess = "PublicAndPrivate"
)

// Valid indicates whether the value is a known member of the GCPClusterPlatformEndpointAccess enum.
func (e GCPClusterPlatformEndpointAccess) Valid() bool {
	switch e {
	case Private:
		return true
	case PublicAndPrivate:
		return true
	default:
		return false
	}
}

// Defines values for GCPRootVolumeType.
const (
	PdBalanced GCPRootVolumeType = "pd-balanced"
	PdSsd      GCPRootVolumeType = "pd-ssd"
	PdStandard GCPRootVolumeType = "pd-standard"
)

// Valid indicates whether the value is a known member of the GCPRootVolumeType enum.
func (e GCPRootVolumeType) Valid() bool {
	switch e {
	case PdBalanced:
		return true
	case PdSsd:
		return true
	case PdStandard:
		return true
	default:
		return false
	}
}

// Defines values for NodePoolPlatformSpecType.
const (
	NodePoolPlatformSpecTypeGcp NodePoolPlatformSpecType = "gcp"
)

// Valid indicates whether the value is a known member of the NodePoolPlatformSpecType enum.
func (e NodePoolPlatformSpecType) Valid() bool {
	switch e {
	case NodePoolPlatformSpecTypeGcp:
		return true
	default:
		return false
	}
}

// Defines values for OrderDirection.
const (
	Asc  OrderDirection = "asc"
	Desc OrderDirection = "desc"
)

// Valid indicates whether the value is a known member of the OrderDirection enum.
func (e OrderDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for ResourceConditionStatus.
const (
	ResourceConditionStatusFalse ResourceConditionStatus = "False"
	ResourceConditionStatusTrue  ResourceConditionStatus = "True"
)

// Valid indicates whether the value is a known member of the ResourceConditionStatus enum.
func (e ResourceConditionStatus) Valid() bool {
	switch e {
	case ResourceConditionStatusFalse:
		return true
	case ResourceConditionStatusTrue:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorConstraint.
const (
	Enum      ValidationErrorConstraint = "enum"
	Format    ValidationErrorConstraint = "format"
	Max       ValidationErrorConstraint = "max"
	MaxLength ValidationErrorConstraint = "max_length"
	Min       ValidationErrorConstraint = "min"
	MinLength ValidationErrorConstraint = "min_length"
	Pattern   ValidationErrorConstraint = "pattern"
	Required  ValidationErrorConstraint = "required"
	Unique    ValidationErrorConstraint = "unique"
)

// Valid indicates whether the value is a known member of the ValidationErrorConstraint enum.
func (e ValidationErrorConstraint) Valid() bool {
	switch e {
	case Enum:
		return true
	case Format:
		return true
	case Max:
		return true
	case MaxLength:
		return true
	case Min:
		return true
	case MinLength:
		return true
	case Pattern:
		return true
	case Required:
		return true
	case Unique:
		return true
	default:
		return false
	}
}

// AdapterCondition Condition in AdapterStatus
// Used for standard Kubernetes condition types: "Available", "Applied", "Health", "Finalized"
// Note: observed_generation is at AdapterStatus level, not per-condition,
// since all conditions in one AdapterStatus share the same observed generation
type AdapterCondition struct {
	// LastTransitionTime When this condition last transitioned status (API-managed)
	// Only updated when status changes (True/False), not when reason/message changes
	LastTransitionTime time.Time `json:"last_transition_time"`

	// Message Human-readable message
	Message *string `json:"message,omitempty"`

	// Reason Machine-readable reason code
	Reason *string `json:"reason,omitempty"`

	// Status Status value for adapter conditions
	Status AdapterConditionStatus `json:"status"`

	// Type Condition type
	Type string `json:"type"`
}

// AdapterConditionStatus Status value for adapter conditions
type AdapterConditionStatus string

// AdapterStatus AdapterStatus represents the complete status report from an adapter
// Contains multiple conditions, job metadata, and adapter-specific data
type AdapterStatus struct {
	// Adapter Adapter name (e.g., "validator", "dns", "provisioner")
	Adapter string `json:"adapter"`

	// Conditions Kubernetes-style conditions tracking adapter state
	// Typically includes: Available, Applied, Health, Finalized
	Conditions []AdapterCondition `json:"conditions"`

	// CreatedTime When this adapter status was first created (API-managed)
	CreatedTime time.Time `json:"created_time"`

	// Data Adapter-specific data (structure varies by adapter type)
	Data *map[string]interface{} `json:"data,omitempty"`

	// LastReportTime When this adapter last reported its status (API-managed)
	// Updated every time the adapter PUTs, even if conditions haven't changed
	// Used by Sentinel to detect adapter liveness
	LastReportTime time.Time `json:"last_report_time"`

	// Metadata Job execution metadata
	Metadata *struct {
		Attempt       *int32     `json:"attempt,omitempty"`
		CompletedTime *time.Time `json:"completed_time,omitempty"`
		Duration      *string    `json:"duration,omitempty"`
		JobName       *string    `json:"job_name,omitempty"`
		JobNamespace  *string    `json:"job_namespace,omitempty"`
		StartedTime   *time.Time `json:"started_time,omitempty"`
	} `json:"metadata,omitempty"`

	// ObservedGeneration Which generation of the resource this status reflects
	ObservedGeneration int32 `json:"observed_generation"`
}

// AdapterStatusList List of adapter statuses with pagination metadata
type AdapterStatusList struct {
	Items []AdapterStatus `json:"items"`
	Page  int32           `json:"page"`
	Size  int32           `json:"size"`
	Total int32           `json:"total"`
}

// BadRequestDetails RFC 9457 Problem Details for HTTP APIs
type BadRequestDetails = ProblemDetails

// Channel defines model for Channel.
type Channel struct {
	// CreatedBy Identity that created the resource
	CreatedBy openapi_types.Email `json:"created_by"`

	// CreatedTime Timestamp when the resource was created
	CreatedTime time.Time `json:"created_time"`

	// DeletedBy Identity that requested deletion; omitted if not marked for deletion
	DeletedBy *openapi_types.Email `json:"deleted_by,omitempty"`

	// DeletedTime Timestamp when deletion was requested; omitted if not marked for deletion
	DeletedTime *time.Time `json:"deleted_time,omitempty"`
	Generation  int32      `json:"generation"`

	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
	Spec   ChannelSpec        `json:"spec"`

	// Status Aggregated status of the resource, populated by the status aggregation
	// pipeline from adapter condition reports.
	Status ResourceStatus `json:"status"`

	// UpdatedBy Identity that last updated the resource
	UpdatedBy openapi_types.Email `json:"updated_by"`

	// UpdatedTime Timestamp when the resource was last updated
	UpdatedTime time.Time `json:"updated_time"`
}

// ChannelCreateRequest defines model for ChannelCreateRequest.
type ChannelCreateRequest struct {
	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
	Spec   ChannelSpec        `json:"spec"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Items []Channel `json:"items"`
	Page  int32     `json:"page"`
	Size  int32     `json:"size"`
	Total int32     `json:"total"`
}

// ChannelPatchRequest defines model for ChannelPatchRequest.
type ChannelPatchRequest struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Spec   *ChannelSpec       `json:"spec,omitempty"`
}

// ChannelSpec defines model for ChannelSpec.
type ChannelSpec struct {
	// EnabledRegex Regex pattern for matching enabled version strings
	EnabledRegex string `json:"enabled_regex"`

	// IsDefault Whether this is the default channel for new clusters
	IsDefault bool `json:"is_default"`
}

// Cluster defines model for Cluster.
type Cluster struct {
	// CreatedBy Identity that created the resource
	CreatedBy openapi_types.Email `json:"created_by"`

	// CreatedTime Timestamp when the resource was created
	CreatedTime time.Time `json:"created_time"`

	// DeletedBy Identity that requested deletion; omitted if not marked for deletion
	DeletedBy *openapi_types.Email `json:"deleted_by,omitempty"`

	// DeletedTime Timestamp when deletion was requested; omitted if not marked for deletion
	DeletedTime *time.Time `json:"deleted_time,omitempty"`

	// Generation Generation field is updated on customer updates, reflecting the version of the "intent" of the customer
	Generation int32 `json:"generation"`

	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Cluster name (unique)
	Name string      `json:"name"`
	Spec ClusterSpec `json:"spec"`

	// Status Cluster status computed from all status conditions.
	//
	// This object is computed by the service and CANNOT be modified directly.
	// It is aggregated from condition updates posted to `/clusters/{id}/statuses`.
	//
	// Provides quick overview of all reported conditions.
	Status ClusterStatus `json:"status"`

	// UpdatedBy Identity that last updated the resource
	UpdatedBy openapi_types.Email `json:"updated_by"`

	// UpdatedTime Timestamp when the resource was last updated
	UpdatedTime time.Time `json:"updated_time"`
}

// ClusterCreateRequest defines model for ClusterCreateRequest.
type ClusterCreateRequest struct {
	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Cluster name (unique)
	Name string      `json:"name"`
	Spec ClusterSpec `json:"spec"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	Items []Cluster `json:"items"`
	Page  int32     `json:"page"`
	Size  int32     `json:"size"`
	Total int32     `json:"total"`
}

// ClusterNetworkEntry defines model for ClusterNetworkEntry.
type ClusterNetworkEntry struct {
	Cidr       *string `json:"cidr,omitempty"`
	HostPrefix *int    `json:"hostPrefix,omitempty"`
}

// ClusterPatchRequest defines model for ClusterPatchRequest.
type ClusterPatchRequest struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Spec   *ClusterSpec       `json:"spec,omitempty"`
}

// ClusterPlatformSpec defines model for ClusterPlatformSpec.
type ClusterPlatformSpec struct {
	Gcp  GCPClusterPlatform      `json:"gcp"`
	Type ClusterPlatformSpecType `json:"type"`
}

// ClusterPlatformSpecType defines model for ClusterPlatformSpec.Type.
type ClusterPlatformSpecType string

// ClusterSpec defines model for ClusterSpec.
type ClusterSpec struct {
	Dns        *DNSSpec            `json:"dns,omitempty"`
	InfraID    *string             `json:"infraID,omitempty"`
	IssuerURL  *string             `json:"issuerURL,omitempty"`
	Networking *NetworkingSpec     `json:"networking,omitempty"`
	Platform   ClusterPlatformSpec `json:"platform"`
	Release    *ReleaseSpec        `json:"release,omitempty"`
}

// ClusterStatus Cluster status computed from all status conditions.
//
// This object is computed by the service and CANNOT be modified directly.
// It is aggregated from condition updates posted to `/clusters/{id}/statuses`.
//
// Provides quick overview of all reported conditions.
type ClusterStatus struct {
	// Conditions List of status conditions for the cluster.
	//
	// **Mandatory conditions**:
	// - `type: "Reconciled"`: Whether the resource's desired state has been fully reconciled by all adapters at the current generation.
	// - `type: "LastKnownReconciled"`: Sticky cross-generation condition — stays True as long as all required adapters were reconciled at a common observed generation, even if a newer generation is being processed.
	//
	// These conditions are present immediately upon resource creation.
	Conditions []ResourceCondition `json:"conditions"`
}

// ConflictDetails RFC 9457 Problem Details for HTTP APIs
type ConflictDetails = ProblemDetails

// DNSSpec defines model for DNSSpec.
type DNSSpec struct {
	BaseDomain *string `json:"baseDomain,omitempty"`
}

// GCPClusterPlatform defines model for GCPClusterPlatform.
type GCPClusterPlatform struct {
	EndpointAccess   *GCPClusterPlatformEndpointAccess `json:"endpointAccess,omitempty"`
	Network          *string                           `json:"network,omitempty"`
	ProjectID        string                            `json:"projectID"`
	Region           string                            `json:"region"`
	Subnet           *string                           `json:"subnet,omitempty"`
	WorkloadIdentity *GCPWorkloadIdentity              `json:"workloadIdentity,omitempty"`
}

// GCPClusterPlatformEndpointAccess defines model for GCPClusterPlatform.EndpointAccess.
type GCPClusterPlatformEndpointAccess string

// GCPNodePoolPlatform defines model for GCPNodePoolPlatform.
type GCPNodePoolPlatform struct {
	// InstanceType GCE machine type (e.g. n2-standard-4). Maps to HyperShift NodePool machineType.
	InstanceType *string `json:"instanceType,omitempty"`

	// RootVolume Boot disk configuration. Maps to HyperShift NodePool bootDisk.
	RootVolume *GCPRootVolume `json:"rootVolume,omitempty"`

	// Zone GCP zone for node placement (e.g. us-central1-a). Falls back to cluster region + "-a" if not set.
	Zone *string `json:"zone,omitempty"`
}

// GCPRootVolume defines model for GCPRootVolume.
type GCPRootVolume struct {
	// Size Boot disk size in GB. Maps to HyperShift bootDisk.diskSizeGB.
	Size *int `json:"size,omitempty"`

	// Type Boot disk type. Maps to HyperShift bootDisk.diskType.
	Type *GCPRootVolumeType `json:"type,omitempty"`
}

// GCPRootVolumeType Boot disk type. Maps to HyperShift bootDisk.diskType.
type GCPRootVolumeType string

// GCPServiceAccountsRef defines model for GCPServiceAccountsRef.
type GCPServiceAccountsRef struct {
	CloudControllerEmail *string `json:"cloudControllerEmail,omitempty"`
	ControlPlaneEmail    *string `json:"controlPlaneEmail,omitempty"`
	ImageRegistryEmail   *string `json:"imageRegistryEmail,omitempty"`
	NetworkEmail         *string `json:"networkEmail,omitempty"`
	NodePoolEmail        *string `json:"nodePoolEmail,omitempty"`
	StorageEmail         *string `json:"storageEmail,omitempty"`
}

// GCPWorkloadIdentity defines model for GCPWorkloadIdentity.
type GCPWorkloadIdentity struct {
	PoolID             string                 `json:"poolID"`
	ProjectNumber      string                 `json:"projectNumber"`
	ProviderID         string                 `json:"providerID"`
	ServiceAccountsRef *GCPServiceAccountsRef `json:"serviceAccountsRef,omitempty"`
}

// NetworkingSpec defines model for NetworkingSpec.
type NetworkingSpec struct {
	ClusterNetwork *[]ClusterNetworkEntry `json:"clusterNetwork,omitempty"`
	ServiceNetwork *[]string              `json:"serviceNetwork,omitempty"`
}

// NodePool defines model for NodePool.
type NodePool struct {
	// CreatedBy Identity that created the resource
	CreatedBy openapi_types.Email `json:"created_by"`

	// CreatedTime Timestamp when the resource was created
	CreatedTime time.Time `json:"created_time"`

	// DeletedBy Identity that requested deletion; omitted if not marked for deletion
	DeletedBy *openapi_types.Email `json:"deleted_by,omitempty"`

	// DeletedTime Timestamp when deletion was requested; omitted if not marked for deletion
	DeletedTime *time.Time `json:"deleted_time,omitempty"`

	// Generation Generation field is updated on customer updates, reflecting the version of the "intent" of the customer
	Generation int32 `json:"generation"`

	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`

	// Name NodePool name (unique in a cluster)
	Name            string          `json:"name"`
	OwnerReferences ObjectReference `json:"owner_references"`
	Spec            NodePoolSpec    `json:"spec"`

	// Status NodePool status computed from all status conditions.
	//
	// This object is computed by the service and CANNOT be modified directly.
	Status NodePoolStatus `json:"status"`

	// UpdatedBy Identity that last updated the resource
	UpdatedBy openapi_types.Email `json:"updated_by"`

	// UpdatedTime Timestamp when the resource was last updated
	UpdatedTime time.Time `json:"updated_time"`
}

// NodePoolCreateRequest defines model for NodePoolCreateRequest.
type NodePoolCreateRequest struct {
	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`

	// Name NodePool name (unique in a cluster)
	Name string       `json:"name"`
	Spec NodePoolSpec `json:"spec"`
}

// NodePoolCreateResponse defines model for NodePoolCreateResponse.
type NodePoolCreateResponse struct {
	// CreatedBy Identity that created the resource
	CreatedBy openapi_types.Email `json:"created_by"`

	// CreatedTime Timestamp when the resource was created
	CreatedTime time.Time `json:"created_time"`

	// DeletedBy Identity that requested deletion; omitted if not marked for deletion
	DeletedBy *openapi_types.Email `json:"deleted_by,omitempty"`

	// DeletedTime Timestamp when deletion was requested; omitted if not marked for deletion
	DeletedTime *time.Time `json:"deleted_time,omitempty"`

	// Generation Generation field is updated on customer updates, reflecting the version of the "intent" of the customer
	Generation int32 `json:"generation"`

	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`

	// Name NodePool name (unique in a cluster)
	Name            string          `json:"name"`
	OwnerReferences ObjectReference `json:"owner_references"`
	Spec            NodePoolSpec    `json:"spec"`

	// Status NodePool status computed from all status conditions.
	//
	// This object is computed by the service and CANNOT be modified directly.
	Status NodePoolStatus `json:"status"`

	// UpdatedBy Identity that last updated the resource
	UpdatedBy openapi_types.Email `json:"updated_by"`

	// UpdatedTime Timestamp when the resource was last updated
	UpdatedTime time.Time `json:"updated_time"`
}

// NodePoolList defines model for NodePoolList.
type NodePoolList struct {
	Items []NodePool `json:"items"`
	Page  int32      `json:"page"`
	Size  int32      `json:"size"`
	Total int32      `json:"total"`
}

// NodePoolPatchRequest defines model for NodePoolPatchRequest.
type NodePoolPatchRequest struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Spec   *NodePoolSpec      `json:"spec,omitempty"`
}

// NodePoolPlatformSpec defines model for NodePoolPlatformSpec.
type NodePoolPlatformSpec struct {
	Gcp  GCPNodePoolPlatform      `json:"gcp"`
	Type NodePoolPlatformSpecType `json:"type"`
}

// NodePoolPlatformSpecType defines model for NodePoolPlatformSpec.Type.
type NodePoolPlatformSpecType string

// NodePoolReleaseSpec defines model for NodePoolReleaseSpec.
type NodePoolReleaseSpec struct {
	// ChannelGroup Cincinnati channel group (e.g. candidate, stable). Combined with version major.minor to derive channel.
	ChannelGroup *string `json:"channelGroup,omitempty"`

	// Version OCP version string (e.g. 4.22.0-rc.5). Resolved to a release image by nodepool-vr-adapter via Cincinnati.
	Version *string `json:"version,omitempty"`
}

// NodePoolSpec defines model for NodePoolSpec.
type NodePoolSpec struct {
	Platform NodePoolPlatformSpec `json:"platform"`
	Release  *NodePoolReleaseSpec `json:"release,omitempty"`
	Replicas *int                 `json:"replicas,omitempty"`
}

// NodePoolStatus NodePool status computed from all status conditions.
//
// This object is computed by the service and CANNOT be modified directly.
type NodePoolStatus struct {
	// Conditions List of status conditions for the nodepool.
	//
	// **Mandatory conditions**:
	// - `type: "Reconciled"`: Whether the resource's desired state has been fully reconciled by all adapters at the current generation.
	// - `type: "LastKnownReconciled"`: Sticky cross-generation condition — stays True as long as all required adapters were reconciled at a common observed generation, even if a newer generation is being processed.
	//
	// These conditions are present immediately upon resource creation.
	Conditions []ResourceCondition `json:"conditions"`
}

// NotFoundDetails RFC 9457 Problem Details for HTTP APIs
type NotFoundDetails = ProblemDetails

// ObjectReference defines model for ObjectReference.
type ObjectReference struct {
	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`
}

// OrderDirection defines model for OrderDirection.
type OrderDirection string

// ProblemDetails RFC 9457 Problem Details for HTTP APIs
type ProblemDetails struct {
	// Code Machine-readable error code in HYPERFLEET-CAT-NUM format
	Code *string `json:"code,omitempty"`

	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors (for validation failures)
	Errors *[]ValidationError `json:"errors,omitempty"`

	// Instance URI reference for this specific occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Timestamp RFC3339 timestamp of when the error occurred
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// TraceId Distributed trace ID for correlation
	TraceId *string `json:"trace_id,omitempty"`

	// Type URI reference identifying the problem type
	Type string `json:"type"`
}

// ReleaseSpec defines model for ReleaseSpec.
type ReleaseSpec struct {
	ChannelGroup *string `json:"channelGroup,omitempty"`
	Image        *string `json:"image,omitempty"`
	Version      *string `json:"version,omitempty"`
}

// ResourceCondition Condition in Cluster/NodePool status
// Used for semantic condition types: "ValidationSuccessful", "DNSSuccessful", "NodePoolSuccessful", etc.
// Includes observed_generation and last_updated_time to track adapter-specific state
type ResourceCondition struct {
	// CreatedTime When this condition was first created (API-managed)
	CreatedTime time.Time `json:"created_time"`

	// LastTransitionTime When this condition last transitioned status (API-managed)
	// Only updated when status changes (True/False), not when reason/message changes
	LastTransitionTime time.Time `json:"last_transition_time"`

	// LastUpdatedTime When the corresponding adapter last reported (API-managed)
	// Updated every time the adapter PUTs, even if condition status hasn't changed
	// Copied from AdapterStatus.last_report_time
	LastUpdatedTime time.Time `json:"last_updated_time"`

	// Message Human-readable message
	Message *string `json:"message,omitempty"`

	// ObservedGeneration Generation of the spec that this condition reflects
	ObservedGeneration int32 `json:"observed_generation"`

	// Reason Machine-readable reason code
	Reason *string `json:"reason,omitempty"`

	// Status Status value for resource conditions
	Status ResourceConditionStatus `json:"status"`

	// Type Condition type
	Type string `json:"type"`
}

// ResourceConditionStatus Status value for resource conditions
type ResourceConditionStatus string

// ResourceStatus Aggregated status of the resource, populated by the status aggregation
// pipeline from adapter condition reports.
type ResourceStatus struct {
	Conditions []ResourceCondition `json:"conditions"`
}

// UnauthorizedDetails RFC 9457 Problem Details for HTTP APIs
type UnauthorizedDetails = ProblemDetails

// ValidationError Field-level validation error detail
type ValidationError struct {
	// Constraint The validation constraint that was violated
	Constraint *ValidationErrorConstraint `json:"constraint,omitempty"`

	// Field JSON path to the field that failed validation
	Field string `json:"field"`

	// Message Human-readable error message for this field
	Message string `json:"message"`

	// Value The invalid value that was provided (if safe to include)
	Value interface{} `json:"value,omitempty"`
}

// ValidationErrorConstraint The validation constraint that was violated
type ValidationErrorConstraint string

// Version defines model for Version.
type Version struct {
	// CreatedBy Identity that created the resource
	CreatedBy openapi_types.Email `json:"created_by"`

	// CreatedTime Timestamp when the resource was created
	CreatedTime time.Time `json:"created_time"`

	// DeletedBy Identity that requested deletion; omitted if not marked for deletion
	DeletedBy *openapi_types.Email `json:"deleted_by,omitempty"`

	// DeletedTime Timestamp when deletion was requested; omitted if not marked for deletion
	DeletedTime *time.Time `json:"deleted_time,omitempty"`
	Generation  int32      `json:"generation"`

	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels          *map[string]string `json:"labels,omitempty"`
	Name            string             `json:"name"`
	OwnerReferences ObjectReference    `json:"owner_references"`
	Spec            VersionSpec        `json:"spec"`

	// Status Aggregated status of the resource, populated by the status aggregation
	// pipeline from adapter condition reports.
	Status ResourceStatus `json:"status"`

	// UpdatedBy Identity that last updated the resource
	UpdatedBy openapi_types.Email `json:"updated_by"`

	// UpdatedTime Timestamp when the resource was last updated
	UpdatedTime time.Time `json:"updated_time"`
}

// VersionCreateRequest defines model for VersionCreateRequest.
type VersionCreateRequest struct {
	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
	Spec   VersionSpec        `json:"spec"`
}

// VersionList defines model for VersionList.
type VersionList struct {
	Items []Version `json:"items"`
	Page  int32     `json:"page"`
	Size  int32     `json:"size"`
	Total int32     `json:"total"`
}

// VersionPatchRequest defines model for VersionPatchRequest.
type VersionPatchRequest struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Spec   *VersionSpec       `json:"spec,omitempty"`
}

// VersionSpec defines model for VersionSpec.
type VersionSpec struct {
	// Enabled Whether this version is enabled for provisioning
	Enabled bool `json:"enabled"`

	// EndOfLifeTime When this version reaches end of life
	EndOfLifeTime *time.Time `json:"end_of_life_time,omitempty"`

	// IsDefault Whether this is the default version for its channel
	IsDefault bool `json:"is_default"`

	// RawVersion Raw version string (e.g., "4.17.12")
	RawVersion string `json:"raw_version"`

	// ReleaseImage Container image reference for the release
	ReleaseImage string `json:"release_image"`
}

// WifConfig defines model for WifConfig.
type WifConfig struct {
	// CreatedBy Identity that created the resource
	CreatedBy openapi_types.Email `json:"created_by"`

	// CreatedTime Timestamp when the resource was created
	CreatedTime time.Time `json:"created_time"`

	// DeletedBy Identity that requested deletion; omitted if not marked for deletion
	DeletedBy *openapi_types.Email `json:"deleted_by,omitempty"`

	// DeletedTime Timestamp when deletion was requested; omitted if not marked for deletion
	DeletedTime *time.Time `json:"deleted_time,omitempty"`
	Generation  int32      `json:"generation"`

	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
	Spec   WifConfigSpec      `json:"spec"`

	// Status Aggregated status of the resource, populated by the status aggregation
	// pipeline from adapter condition reports.
	Status ResourceStatus `json:"status"`

	// UpdatedBy Identity that last updated the resource
	UpdatedBy openapi_types.Email `json:"updated_by"`

	// UpdatedTime Timestamp when the resource was last updated
	UpdatedTime time.Time `json:"updated_time"`
}

// WifConfigCreateRequest defines model for WifConfigCreateRequest.
type WifConfigCreateRequest struct {
	// Href Resource URI
	Href *string `json:"href,omitempty"`

	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind *string `json:"kind,omitempty"`

	// Labels labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
	Spec   WifConfigSpec      `json:"spec"`
}

// WifConfigList defines model for WifConfigList.
type WifConfigList struct {
	Items []WifConfig `json:"items"`
	Page  int32       `json:"page"`
	Size  int32       `json:"size"`
	Total int32       `json:"total"`
}

// WifConfigPatchRequest defines model for WifConfigPatchRequest.
type WifConfigPatchRequest struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Spec   *WifConfigSpec     `json:"spec,omitempty"`
}

// WifConfigSpec defines model for WifConfigSpec.
type WifConfigSpec struct {
	// ProjectId GCP project identifier
	ProjectId string `json:"project_id"`

	// Version Version of the WIF configuration
	Version string `json:"version"`
}

// QueryParamsOrder defines model for QueryParams.order.
type QueryParamsOrder = OrderDirection

// QueryParamsOrderBy defines model for QueryParams.orderBy.
type QueryParamsOrderBy = string

// QueryParamsPage defines model for QueryParams.page.
type QueryParamsPage = int32

// QueryParamsPageSize defines model for QueryParams.pageSize.
type QueryParamsPageSize = int32

// SearchParams defines model for SearchParams.
type SearchParams = string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetChannelsParams defines parameters for GetChannels.
type GetChannelsParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search   *SearchParams        `form:"search,omitempty" json:"search,omitempty"`
	Page     *QueryParamsPage     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *QueryParamsPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OrderBy  *QueryParamsOrderBy  `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	Order    *QueryParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
}

// GetChannelByIdParams defines parameters for GetChannelById.
type GetChannelByIdParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search *SearchParams `form:"search,omitempty" json:"search,omitempty"`
}

// GetVersionsByChannelIdParams defines parameters for GetVersionsByChannelId.
type GetVersionsByChannelIdParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search   *SearchParams        `form:"search,omitempty" json:"search,omitempty"`
	Page     *QueryParamsPage     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *QueryParamsPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OrderBy  *QueryParamsOrderBy  `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	Order    *QueryParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
}

// GetClustersParams defines parameters for GetClusters.
type GetClustersParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search   *SearchParams        `form:"search,omitempty" json:"search,omitempty"`
	Page     *QueryParamsPage     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *QueryParamsPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OrderBy  *QueryParamsOrderBy  `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	Order    *QueryParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
}

// GetClusterByIdParams defines parameters for GetClusterById.
type GetClusterByIdParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search *SearchParams `form:"search,omitempty" json:"search,omitempty"`
}

// GetNodePoolsByClusterIdParams defines parameters for GetNodePoolsByClusterId.
type GetNodePoolsByClusterIdParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search   *SearchParams        `form:"search,omitempty" json:"search,omitempty"`
	Page     *QueryParamsPage     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *QueryParamsPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OrderBy  *QueryParamsOrderBy  `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	Order    *QueryParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
}

// GetNodePoolsParams defines parameters for GetNodePools.
type GetNodePoolsParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search   *SearchParams        `form:"search,omitempty" json:"search,omitempty"`
	Page     *QueryParamsPage     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *QueryParamsPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OrderBy  *QueryParamsOrderBy  `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	Order    *QueryParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
}

// GetWifConfigsParams defines parameters for GetWifConfigs.
type GetWifConfigsParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search   *SearchParams        `form:"search,omitempty" json:"search,omitempty"`
	Page     *QueryParamsPage     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *QueryParamsPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OrderBy  *QueryParamsOrderBy  `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	Order    *QueryParamsOrder    `form:"order,omitempty" json:"order,omitempty"`
}

// GetWifConfigByIdParams defines parameters for GetWifConfigById.
type GetWifConfigByIdParams struct {
	// Search Filter results using TSL (Tree Search Language) query syntax.
	// Examples: `status.conditions.Reconciled='True'`, `name in ('c1','c2')`, `labels.region='us-east'`
	Search *SearchParams `form:"search,omitempty" json:"search,omitempty"`
}

// PostChannelJSONRequestBody defines body for PostChannel for application/json ContentType.
type PostChannelJSONRequestBody = ChannelCreateRequest

// PatchChannelByIdJSONRequestBody defines body for PatchChannelById for application/json ContentType.
type PatchChannelByIdJSONRequestBody = ChannelPatchRequest

// PostVersionJSONRequestBody defines body for PostVersion for application/json ContentType.
type PostVersionJSONRequestBody = VersionCreateRequest

// PatchVersionByIdJSONRequestBody defines body for PatchVersionById for application/json ContentType.
type PatchVersionByIdJSONRequestBody = VersionPatchRequest

// PostClusterJSONRequestBody defines body for PostCluster for application/json ContentType.
type PostClusterJSONRequestBody = ClusterCreateRequest

// PatchClusterByIdJSONRequestBody defines body for PatchClusterById for application/json ContentType.
type PatchClusterByIdJSONRequestBody = ClusterPatchRequest

// CreateNodePoolJSONRequestBody defines body for CreateNodePool for application/json ContentType.
type CreateNodePoolJSONRequestBody = NodePoolCreateRequest

// PatchNodePoolByIdJSONRequestBody defines body for PatchNodePoolById for application/json ContentType.
type PatchNodePoolByIdJSONRequestBody = NodePoolPatchRequest

// PostWifConfigJSONRequestBody defines body for PostWifConfig for application/json ContentType.
type PostWifConfigJSONRequestBody = WifConfigCreateRequest

// PatchWifConfigByIdJSONRequestBody defines body for PatchWifConfigById for application/json ContentType.
type PatchWifConfigByIdJSONRequestBody = WifConfigPatchRequest
